// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// S4sprval
NumericVector S4sprval(S4 fullstack, NumericVector angle);
RcppExport SEXP FBFoptics_S4sprval(SEXP fullstackSEXP, SEXP angleSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type angle(angleSEXP );
        NumericVector __result = S4sprval(fullstack, angle);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// S4spr
NumericVector S4spr(S4 fullstack);
RcppExport SEXP FBFoptics_S4spr(SEXP fullstackSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP );
        NumericVector __result = S4spr(fullstack);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// S4sprmin
NumericVector S4sprmin(S4 fullstack);
RcppExport SEXP FBFoptics_S4sprmin(SEXP fullstackSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP );
        NumericVector __result = S4sprmin(fullstack);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
