// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// S4_SPRVAL
NumericVector S4_SPRVAL(S4 fullstack, NumericVector angle);
RcppExport SEXP FBFoptics_S4_SPRVAL(SEXP fullstackSEXP, SEXP angleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type angle(angleSEXP);
    rcpp_result_gen = Rcpp::wrap(S4_SPRVAL(fullstack, angle));
    return rcpp_result_gen;
END_RCPP
}
// S4_DELTAVAL
NumericVector S4_DELTAVAL(S4 fullstack, NumericVector angle);
RcppExport SEXP FBFoptics_S4_DELTAVAL(SEXP fullstackSEXP, SEXP angleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type angle(angleSEXP);
    rcpp_result_gen = Rcpp::wrap(S4_DELTAVAL(fullstack, angle));
    return rcpp_result_gen;
END_RCPP
}
// S4_SPRG
NumericVector S4_SPRG(S4 fullstack);
RcppExport SEXP FBFoptics_S4_SPRG(SEXP fullstackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP);
    rcpp_result_gen = Rcpp::wrap(S4_SPRG(fullstack));
    return rcpp_result_gen;
END_RCPP
}
// S4_SPRD
NumericVector S4_SPRD(S4 fullstack);
RcppExport SEXP FBFoptics_S4_SPRD(SEXP fullstackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP);
    rcpp_result_gen = Rcpp::wrap(S4_SPRD(fullstack));
    return rcpp_result_gen;
END_RCPP
}
// S4_SPRMIN
NumericVector S4_SPRMIN(S4 fullstack);
RcppExport SEXP FBFoptics_S4_SPRMIN(SEXP fullstackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP);
    rcpp_result_gen = Rcpp::wrap(S4_SPRMIN(fullstack));
    return rcpp_result_gen;
END_RCPP
}
// S4_SPRI
NumericVector S4_SPRI(S4 fullstack);
RcppExport SEXP FBFoptics_S4_SPRI(SEXP fullstackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type fullstack(fullstackSEXP);
    rcpp_result_gen = Rcpp::wrap(S4_SPRI(fullstack));
    return rcpp_result_gen;
END_RCPP
}
