# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

S4_SPRVAL <- function(fullstack, angle) {
    .Call('FBFoptics_S4_SPRVAL', PACKAGE = 'FBFoptics', fullstack, angle)
}

S4_DELTAVAL <- function(fullstack, angle) {
    .Call('FBFoptics_S4_DELTAVAL', PACKAGE = 'FBFoptics', fullstack, angle)
}

S4_SPRG_RPP <- function(fullstack) {
    .Call('FBFoptics_S4_SPRG_RPP', PACKAGE = 'FBFoptics', fullstack)
}

S4_SPRG_DELTA <- function(fullstack) {
    .Call('FBFoptics_S4_SPRG_DELTA', PACKAGE = 'FBFoptics', fullstack)
}

S4_SPRD <- function(fullstack) {
    .Call('FBFoptics_S4_SPRD', PACKAGE = 'FBFoptics', fullstack)
}

S4_SPRMIN <- function(fullstack) {
    .Call('FBFoptics_S4_SPRMIN', PACKAGE = 'FBFoptics', fullstack)
}

S4_SPRI <- function(fullstack) {
    .Call('FBFoptics_S4_SPRI', PACKAGE = 'FBFoptics', fullstack)
}

